env: local
storage:
  path: localhost:54321
httpServer:
  address: "0.0.0.0:8081"
images:
  basePath: "./static/users/upload/"
  avatarsPath: "./static/users/upload/avatars/"
#  defaultAdminImageURL: "/static/users/upload/default/admin.jpg"